name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_oFquf2pER7k4qjQQImtrxeBT
          VERCEL_PROJECT_ID: prj_5JYOcD8sNJl8AASxkMUkfD6EdnpD
